export const CHAMPIONS = [
  {
    id: "Aatrox",
    key: "266",
    name: "Aatrox",
    title: "the Darkin Blade",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Aatrox.png",
      sprite: "champion0.png",
      group: "champion",
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ahri",
    key: "103",
    name: "Ahri",
    title: "the Nine-Tailed Fox",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Ahri.png",
      sprite: "champion0.png",
      group: "champion",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Akali",
    key: "84",
    name: "Akali",
    title: "the Rogue Assassin",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Akali.png",
      sprite: "champion0.png",
      group: "champion",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Akshan",
    key: "166",
    name: "Akshan",
    title: "the Rogue Sentinel",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Akshan.png",
      sprite: "champion0.png",
      group: "champion",
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Alistar",
    key: "12",
    name: "Alistar",
    title: "the Minotaur",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Alistar.png",
      sprite: "champion0.png",
      group: "champion",
      x: 192,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Amumu",
    key: "32",
    name: "Amumu",
    title: "the Sad Mummy",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Amumu.png",
      sprite: "champion0.png",
      group: "champion",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Anivia",
    key: "34",
    name: "Anivia",
    title: "the Cryophoenix",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Anivia.png",
      sprite: "champion0.png",
      group: "champion",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Annie",
    key: "1",
    name: "Annie",
    title: "the Dark Child",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Annie.png",
      sprite: "champion0.png",
      group: "champion",
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Aphelios",
    key: "523",
    name: "Aphelios",
    title: "the Weapon of the Faithful",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Aphelios.png",
      sprite: "champion0.png",
      group: "champion",
      x: 384,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ashe",
    key: "22",
    name: "Ashe",
    title: "the Frost Archer",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Ashe.png",
      sprite: "champion0.png",
      group: "champion",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "AurelionSol",
    key: "136",
    name: "Aurelion Sol",
    title: "The Star Forger",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "AurelionSol.png",
      sprite: "champion0.png",
      group: "champion",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Azir",
    key: "268",
    name: "Azir",
    title: "the Emperor of the Sands",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Azir.png",
      sprite: "champion0.png",
      group: "champion",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Bard",
    key: "432",
    name: "Bard",
    title: "the Wandering Caretaker",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Bard.png",
      sprite: "champion0.png",
      group: "champion",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Belveth",
    key: "200",
    name: "Bel'Veth",
    title: "the Empress of the Void",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Belveth.png",
      sprite: "champion0.png",
      group: "champion",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Blitzcrank",
    key: "53",
    name: "Blitzcrank",
    title: "the Great Steam Golem",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Blitzcrank.png",
      sprite: "champion0.png",
      group: "champion",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Brand",
    key: "63",
    name: "Brand",
    title: "the Burning Vengeance",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Brand.png",
      sprite: "champion0.png",
      group: "champion",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Braum",
    key: "201",
    name: "Braum",
    title: "the Heart of the Freljord",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Braum.png",
      sprite: "champion0.png",
      group: "champion",
      x: 288,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Briar",
    key: "233",
    name: "Briar",
    title: "the Restrained Hunger",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Briar.png",
      sprite: "champion0.png",
      group: "champion",
      x: 336,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Caitlyn",
    key: "51",
    name: "Caitlyn",
    title: "the Sheriff of Piltover",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Caitlyn.png",
      sprite: "champion0.png",
      group: "champion",
      x: 384,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Camille",
    key: "164",
    name: "Camille",
    title: "the Steel Shadow",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Camille.png",
      sprite: "champion0.png",
      group: "champion",
      x: 432,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Cassiopeia",
    key: "69",
    name: "Cassiopeia",
    title: "the Serpent's Embrace",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Cassiopeia.png",
      sprite: "champion0.png",
      group: "champion",
      x: 0,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Chogath",
    key: "31",
    name: "Cho'Gath",
    title: "the Terror of the Void",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Chogath.png",
      sprite: "champion0.png",
      group: "champion",
      x: 48,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Corki",
    key: "42",
    name: "Corki",
    title: "the Daring Bombardier",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Corki.png",
      sprite: "champion0.png",
      group: "champion",
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Darius",
    key: "122",
    name: "Darius",
    title: "the Hand of Noxus",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Darius.png",
      sprite: "champion0.png",
      group: "champion",
      x: 144,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Diana",
    key: "131",
    name: "Diana",
    title: "Scorn of the Moon",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Diana.png",
      sprite: "champion0.png",
      group: "champion",
      x: 192,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Draven",
    key: "119",
    name: "Draven",
    title: "the Glorious Executioner",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Draven.png",
      sprite: "champion0.png",
      group: "champion",
      x: 240,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "DrMundo",
    key: "36",
    name: "Dr. Mundo",
    title: "the Madman of Zaun",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "DrMundo.png",
      sprite: "champion0.png",
      group: "champion",
      x: 288,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ekko",
    key: "245",
    name: "Ekko",
    title: "the Boy Who Shattered Time",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Ekko.png",
      sprite: "champion0.png",
      group: "champion",
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Elise",
    key: "60",
    name: "Elise",
    title: "the Spider Queen",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Elise.png",
      sprite: "champion0.png",
      group: "champion",
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Evelynn",
    key: "28",
    name: "Evelynn",
    title: "Agony's Embrace",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion0.png",
    image: {
      full: "Evelynn.png",
      sprite: "champion0.png",
      group: "champion",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ezreal",
    key: "81",
    name: "Ezreal",
    title: "the Prodigal Explorer",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Ezreal.png",
      sprite: "champion1.png",
      group: "champion",
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "FiddleSticks",
    key: "9",
    name: "FiddleSticks",
    title: "the Ancient Fear",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "FiddleSticks.png",
      sprite: "champion1.png",
      group: "champion",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Fiora",
    key: "114",
    name: "Fiora",
    title: "the Grand Duelist",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Fiora.png",
      sprite: "champion1.png",
      group: "champion",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Fizz",
    key: "105",
    name: "Fizz",
    title: "the Tidal Trickster",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Fizz.png",
      sprite: "champion1.png",
      group: "champion",
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Galio",
    key: "3",
    name: "Galio",
    title: "the Colossus",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Galio.png",
      sprite: "champion1.png",
      group: "champion",
      x: 192,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Gangplank",
    key: "41",
    name: "Gangplank",
    title: "the Saltwater Scourge",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Gangplank.png",
      sprite: "champion1.png",
      group: "champion",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Garen",
    key: "86",
    name: "Garen",
    title: "The Might of Demacia",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Garen.png",
      sprite: "champion1.png",
      group: "champion",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Gnar",
    key: "150",
    name: "Gnar",
    title: "the Missing Link",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Gnar.png",
      sprite: "champion1.png",
      group: "champion",
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Gragas",
    key: "79",
    name: "Gragas",
    title: "the Rabble Rouser",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Gragas.png",
      sprite: "champion1.png",
      group: "champion",
      x: 384,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Graves",
    key: "104",
    name: "Graves",
    title: "the Outlaw",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Graves.png",
      sprite: "champion1.png",
      group: "champion",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Gwen",
    key: "887",
    name: "Gwen",
    title: "The Hallowed Seamstress",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Gwen.png",
      sprite: "champion1.png",
      group: "champion",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Hecarim",
    key: "120",
    name: "Hecarim",
    title: "the Shadow of War",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Hecarim.png",
      sprite: "champion1.png",
      group: "champion",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Heimerdinger",
    key: "74",
    name: "Heimerdinger",
    title: "the Revered Inventor",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Heimerdinger.png",
      sprite: "champion1.png",
      group: "champion",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Illaoi",
    key: "420",
    name: "Illaoi",
    title: "the Kraken Priestess",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Illaoi.png",
      sprite: "champion1.png",
      group: "champion",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Irelia",
    key: "39",
    name: "Irelia",
    title: "the Blade Dancer",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Irelia.png",
      sprite: "champion1.png",
      group: "champion",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ivern",
    key: "427",
    name: "Ivern",
    title: "the Green Father",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Ivern.png",
      sprite: "champion1.png",
      group: "champion",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Janna",
    key: "40",
    name: "Janna",
    title: "the Storm's Fury",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Janna.png",
      sprite: "champion1.png",
      group: "champion",
      x: 288,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "JarvanIV",
    key: "59",
    name: "Jarvan IV",
    title: "the Exemplar of Demacia",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "JarvanIV.png",
      sprite: "champion1.png",
      group: "champion",
      x: 336,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Jax",
    key: "24",
    name: "Jax",
    title: "Grandmaster at Arms",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Jax.png",
      sprite: "champion1.png",
      group: "champion",
      x: 384,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Jayce",
    key: "126",
    name: "Jayce",
    title: "the Defender of Tomorrow",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Jayce.png",
      sprite: "champion1.png",
      group: "champion",
      x: 432,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Jhin",
    key: "202",
    name: "Jhin",
    title: "the Virtuoso",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Jhin.png",
      sprite: "champion1.png",
      group: "champion",
      x: 0,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Jinx",
    key: "222",
    name: "Jinx",
    title: "the Loose Cannon",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Jinx.png",
      sprite: "champion1.png",
      group: "champion",
      x: 48,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kaisa",
    key: "145",
    name: "Kai'Sa",
    title: "Daughter of the Void",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Kaisa.png",
      sprite: "champion1.png",
      group: "champion",
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kalista",
    key: "429",
    name: "Kalista",
    title: "the Spear of Vengeance",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Kalista.png",
      sprite: "champion1.png",
      group: "champion",
      x: 144,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Karma",
    key: "43",
    name: "Karma",
    title: "the Enlightened One",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Karma.png",
      sprite: "champion1.png",
      group: "champion",
      x: 192,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Karthus",
    key: "30",
    name: "Karthus",
    title: "the Deathsinger",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Karthus.png",
      sprite: "champion1.png",
      group: "champion",
      x: 240,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kassadin",
    key: "38",
    name: "Kassadin",
    title: "the Void Walker",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Kassadin.png",
      sprite: "champion1.png",
      group: "champion",
      x: 288,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Katarina",
    key: "55",
    name: "Katarina",
    title: "the Sinister Blade",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Katarina.png",
      sprite: "champion1.png",
      group: "champion",
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kayle",
    key: "10",
    name: "Kayle",
    title: "the Righteous",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Kayle.png",
      sprite: "champion1.png",
      group: "champion",
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kayn",
    key: "141",
    name: "Kayn",
    title: "the Shadow Reaper",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion1.png",
    image: {
      full: "Kayn.png",
      sprite: "champion1.png",
      group: "champion",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kennen",
    key: "85",
    name: "Kennen",
    title: "the Heart of the Tempest",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Kennen.png",
      sprite: "champion2.png",
      group: "champion",
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Khazix",
    key: "121",
    name: "Kha'Zix",
    title: "the Voidreaver",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Khazix.png",
      sprite: "champion2.png",
      group: "champion",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kindred",
    key: "203",
    name: "Kindred",
    title: "The Eternal Hunters",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Kindred.png",
      sprite: "champion2.png",
      group: "champion",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Kled",
    key: "240",
    name: "Kled",
    title: "the Cantankerous Cavalier",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Kled.png",
      sprite: "champion2.png",
      group: "champion",
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "KogMaw",
    key: "96",
    name: "Kog'Maw",
    title: "the Mouth of the Abyss",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "KogMaw.png",
      sprite: "champion2.png",
      group: "champion",
      x: 192,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "KSante",
    key: "897",
    name: "K'Sante",
    title: "the Pride of Nazumah",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "KSante.png",
      sprite: "champion2.png",
      group: "champion",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Leblanc",
    key: "7",
    name: "LeBlanc",
    title: "the Deceiver",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Leblanc.png",
      sprite: "champion2.png",
      group: "champion",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "LeeSin",
    key: "64",
    name: "Lee Sin",
    title: "the Blind Monk",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "LeeSin.png",
      sprite: "champion2.png",
      group: "champion",
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Leona",
    key: "89",
    name: "Leona",
    title: "the Radiant Dawn",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Leona.png",
      sprite: "champion2.png",
      group: "champion",
      x: 384,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Lillia",
    key: "876",
    name: "Lillia",
    title: "the Bashful Bloom",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Lillia.png",
      sprite: "champion2.png",
      group: "champion",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Lissandra",
    key: "127",
    name: "Lissandra",
    title: "the Ice Witch",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Lissandra.png",
      sprite: "champion2.png",
      group: "champion",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Lucian",
    key: "236",
    name: "Lucian",
    title: "the Purifier",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Lucian.png",
      sprite: "champion2.png",
      group: "champion",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Lulu",
    key: "117",
    name: "Lulu",
    title: "the Fae Sorceress",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Lulu.png",
      sprite: "champion2.png",
      group: "champion",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Lux",
    key: "99",
    name: "Lux",
    title: "the Lady of Luminosity",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Lux.png",
      sprite: "champion2.png",
      group: "champion",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Malphite",
    key: "54",
    name: "Malphite",
    title: "Shard of the Monolith",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Malphite.png",
      sprite: "champion2.png",
      group: "champion",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Malzahar",
    key: "90",
    name: "Malzahar",
    title: "the Prophet of the Void",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Malzahar.png",
      sprite: "champion2.png",
      group: "champion",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Maokai",
    key: "57",
    name: "Maokai",
    title: "the Twisted Treant",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Maokai.png",
      sprite: "champion2.png",
      group: "champion",
      x: 288,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "MasterYi",
    key: "11",
    name: "Master Yi",
    title: "the Wuju Bladesman",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "MasterYi.png",
      sprite: "champion2.png",
      group: "champion",
      x: 336,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Milio",
    key: "902",
    name: "Milio",
    title: "The Gentle Flame",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Milio.png",
      sprite: "champion2.png",
      group: "champion",
      x: 384,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "MissFortune",
    key: "21",
    name: "Miss Fortune",
    title: "the Bounty Hunter",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "MissFortune.png",
      sprite: "champion2.png",
      group: "champion",
      x: 432,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "MonkeyKing",
    key: "62",
    name: "Wukong",
    title: "the Monkey King",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "MonkeyKing.png",
      sprite: "champion2.png",
      group: "champion",
      x: 0,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Mordekaiser",
    key: "82",
    name: "Mordekaiser",
    title: "the Iron Revenant",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Mordekaiser.png",
      sprite: "champion2.png",
      group: "champion",
      x: 48,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Morgana",
    key: "25",
    name: "Morgana",
    title: "the Fallen",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Morgana.png",
      sprite: "champion2.png",
      group: "champion",
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Naafiri",
    key: "950",
    name: "Naafiri",
    title: "the Hound of a Hundred Bites",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Naafiri.png",
      sprite: "champion2.png",
      group: "champion",
      x: 144,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Nami",
    key: "267",
    name: "Nami",
    title: "the Tidecaller",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Nami.png",
      sprite: "champion2.png",
      group: "champion",
      x: 192,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Nasus",
    key: "75",
    name: "Nasus",
    title: "the Curator of the Sands",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Nasus.png",
      sprite: "champion2.png",
      group: "champion",
      x: 240,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Nautilus",
    key: "111",
    name: "Nautilus",
    title: "the Titan of the Depths",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Nautilus.png",
      sprite: "champion2.png",
      group: "champion",
      x: 288,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Neeko",
    key: "518",
    name: "Neeko",
    title: "the Curious Chameleon",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Neeko.png",
      sprite: "champion2.png",
      group: "champion",
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Nidalee",
    key: "76",
    name: "Nidalee",
    title: "the Bestial Huntress",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Nidalee.png",
      sprite: "champion2.png",
      group: "champion",
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Nilah",
    key: "895",
    name: "Nilah",
    title: "the Joy Unbound",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion2.png",
    image: {
      full: "Nilah.png",
      sprite: "champion2.png",
      group: "champion",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Nocturne",
    key: "56",
    name: "Nocturne",
    title: "the Eternal Nightmare",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Nocturne.png",
      sprite: "champion3.png",
      group: "champion",
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Nunu",
    key: "20",
    name: "Nunu & Willump",
    title: "the Boy and His Yeti",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Nunu.png",
      sprite: "champion3.png",
      group: "champion",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Olaf",
    key: "2",
    name: "Olaf",
    title: "the Berserker",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Olaf.png",
      sprite: "champion3.png",
      group: "champion",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Orianna",
    key: "61",
    name: "Orianna",
    title: "the Lady of Clockwork",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Orianna.png",
      sprite: "champion3.png",
      group: "champion",
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ornn",
    key: "516",
    name: "Ornn",
    title: "The Fire below the Mountain",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Ornn.png",
      sprite: "champion3.png",
      group: "champion",
      x: 192,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Pantheon",
    key: "80",
    name: "Pantheon",
    title: "the Unbreakable Spear",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Pantheon.png",
      sprite: "champion3.png",
      group: "champion",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Poppy",
    key: "78",
    name: "Poppy",
    title: "Keeper of the Hammer",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Poppy.png",
      sprite: "champion3.png",
      group: "champion",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Pyke",
    key: "555",
    name: "Pyke",
    title: "the Bloodharbor Ripper",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Pyke.png",
      sprite: "champion3.png",
      group: "champion",
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Qiyana",
    key: "246",
    name: "Qiyana",
    title: "Empress of the Elements",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Qiyana.png",
      sprite: "champion3.png",
      group: "champion",
      x: 384,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Quinn",
    key: "133",
    name: "Quinn",
    title: "Demacia's Wings",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Quinn.png",
      sprite: "champion3.png",
      group: "champion",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Rakan",
    key: "497",
    name: "Rakan",
    title: "The Charmer",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Rakan.png",
      sprite: "champion3.png",
      group: "champion",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Rammus",
    key: "33",
    name: "Rammus",
    title: "the Armordillo",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Rammus.png",
      sprite: "champion3.png",
      group: "champion",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "RekSai",
    key: "421",
    name: "Rek'Sai",
    title: "the Void Burrower",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "RekSai.png",
      sprite: "champion3.png",
      group: "champion",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Rell",
    key: "526",
    name: "Rell",
    title: "the Iron Maiden",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Rell.png",
      sprite: "champion3.png",
      group: "champion",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Renata",
    key: "888",
    name: "Renata Glasc",
    title: "the Chem-Baroness",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Renata.png",
      sprite: "champion3.png",
      group: "champion",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Renekton",
    key: "58",
    name: "Renekton",
    title: "the Butcher of the Sands",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Renekton.png",
      sprite: "champion3.png",
      group: "champion",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Rengar",
    key: "107",
    name: "Rengar",
    title: "the Pridestalker",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Rengar.png",
      sprite: "champion3.png",
      group: "champion",
      x: 288,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Riven",
    key: "92",
    name: "Riven",
    title: "the Exile",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Riven.png",
      sprite: "champion3.png",
      group: "champion",
      x: 336,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Rumble",
    key: "68",
    name: "Rumble",
    title: "the Mechanized Menace",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Rumble.png",
      sprite: "champion3.png",
      group: "champion",
      x: 384,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ryze",
    key: "13",
    name: "Ryze",
    title: "the Rune Mage",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Ryze.png",
      sprite: "champion3.png",
      group: "champion",
      x: 432,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Samira",
    key: "360",
    name: "Samira",
    title: "the Desert Rose",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Samira.png",
      sprite: "champion3.png",
      group: "champion",
      x: 0,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Sejuani",
    key: "113",
    name: "Sejuani",
    title: "Fury of the North",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Sejuani.png",
      sprite: "champion3.png",
      group: "champion",
      x: 48,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Senna",
    key: "235",
    name: "Senna",
    title: "the Redeemer",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Senna.png",
      sprite: "champion3.png",
      group: "champion",
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Seraphine",
    key: "147",
    name: "Seraphine",
    title: "the Starry-Eyed Songstress",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Seraphine.png",
      sprite: "champion3.png",
      group: "champion",
      x: 144,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Sett",
    key: "875",
    name: "Sett",
    title: "the Boss",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Sett.png",
      sprite: "champion3.png",
      group: "champion",
      x: 192,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Shaco",
    key: "35",
    name: "Shaco",
    title: "the Demon Jester",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Shaco.png",
      sprite: "champion3.png",
      group: "champion",
      x: 240,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Shen",
    key: "98",
    name: "Shen",
    title: "the Eye of Twilight",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Shen.png",
      sprite: "champion3.png",
      group: "champion",
      x: 288,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Shyvana",
    key: "102",
    name: "Shyvana",
    title: "the Half-Dragon",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Shyvana.png",
      sprite: "champion3.png",
      group: "champion",
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Singed",
    key: "27",
    name: "Singed",
    title: "the Mad Chemist",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Singed.png",
      sprite: "champion3.png",
      group: "champion",
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Sion",
    key: "14",
    name: "Sion",
    title: "The Undead Juggernaut",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion3.png",
    image: {
      full: "Sion.png",
      sprite: "champion3.png",
      group: "champion",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Sivir",
    key: "15",
    name: "Sivir",
    title: "the Battle Mistress",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Sivir.png",
      sprite: "champion4.png",
      group: "champion",
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Skarner",
    key: "72",
    name: "Skarner",
    title: "the Crystal Vanguard",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Skarner.png",
      sprite: "champion4.png",
      group: "champion",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Sona",
    key: "37",
    name: "Sona",
    title: "Maven of the Strings",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Sona.png",
      sprite: "champion4.png",
      group: "champion",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Soraka",
    key: "16",
    name: "Soraka",
    title: "the Starchild",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Soraka.png",
      sprite: "champion4.png",
      group: "champion",
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Swain",
    key: "50",
    name: "Swain",
    title: "the Noxian Grand General",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Swain.png",
      sprite: "champion4.png",
      group: "champion",
      x: 192,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Sylas",
    key: "517",
    name: "Sylas",
    title: "the Unshackled",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Sylas.png",
      sprite: "champion4.png",
      group: "champion",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Syndra",
    key: "134",
    name: "Syndra",
    title: "the Dark Sovereign",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Syndra.png",
      sprite: "champion4.png",
      group: "champion",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "TahmKench",
    key: "223",
    name: "Tahm Kench",
    title: "The River King",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "TahmKench.png",
      sprite: "champion4.png",
      group: "champion",
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Taliyah",
    key: "163",
    name: "Taliyah",
    title: "the Stoneweaver",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Taliyah.png",
      sprite: "champion4.png",
      group: "champion",
      x: 384,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Talon",
    key: "91",
    name: "Talon",
    title: "the Blade's Shadow",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Talon.png",
      sprite: "champion4.png",
      group: "champion",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Taric",
    key: "44",
    name: "Taric",
    title: "the Shield of Valoran",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Taric.png",
      sprite: "champion4.png",
      group: "champion",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Teemo",
    key: "17",
    name: "Teemo",
    title: "the Swift Scout",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Teemo.png",
      sprite: "champion4.png",
      group: "champion",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Thresh",
    key: "412",
    name: "Thresh",
    title: "the Chain Warden",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Thresh.png",
      sprite: "champion4.png",
      group: "champion",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Tristana",
    key: "18",
    name: "Tristana",
    title: "the Yordle Gunner",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Tristana.png",
      sprite: "champion4.png",
      group: "champion",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Trundle",
    key: "48",
    name: "Trundle",
    title: "the Troll King",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Trundle.png",
      sprite: "champion4.png",
      group: "champion",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Tryndamere",
    key: "23",
    name: "Tryndamere",
    title: "the Barbarian King",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Tryndamere.png",
      sprite: "champion4.png",
      group: "champion",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "TwistedFate",
    key: "4",
    name: "Twisted Fate",
    title: "the Card Master",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "TwistedFate.png",
      sprite: "champion4.png",
      group: "champion",
      x: 288,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Twitch",
    key: "29",
    name: "Twitch",
    title: "the Plague Rat",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Twitch.png",
      sprite: "champion4.png",
      group: "champion",
      x: 336,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Udyr",
    key: "77",
    name: "Udyr",
    title: "the Spirit Walker",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Udyr.png",
      sprite: "champion4.png",
      group: "champion",
      x: 384,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Urgot",
    key: "6",
    name: "Urgot",
    title: "the Dreadnought",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Urgot.png",
      sprite: "champion4.png",
      group: "champion",
      x: 432,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Varus",
    key: "110",
    name: "Varus",
    title: "the Arrow of Retribution",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Varus.png",
      sprite: "champion4.png",
      group: "champion",
      x: 0,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Vayne",
    key: "67",
    name: "Vayne",
    title: "the Night Hunter",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Vayne.png",
      sprite: "champion4.png",
      group: "champion",
      x: 48,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Veigar",
    key: "45",
    name: "Veigar",
    title: "the Tiny Master of Evil",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Veigar.png",
      sprite: "champion4.png",
      group: "champion",
      x: 96,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Velkoz",
    key: "161",
    name: "Vel'Koz",
    title: "the Eye of the Void",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Velkoz.png",
      sprite: "champion4.png",
      group: "champion",
      x: 144,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Vex",
    key: "711",
    name: "Vex",
    title: "the Gloomist",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Vex.png",
      sprite: "champion4.png",
      group: "champion",
      x: 192,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Vi",
    key: "254",
    name: "Vi",
    title: "the Piltover Enforcer",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Vi.png",
      sprite: "champion4.png",
      group: "champion",
      x: 240,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Viego",
    key: "234",
    name: "Viego",
    title: "The Ruined King",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Viego.png",
      sprite: "champion4.png",
      group: "champion",
      x: 288,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Viktor",
    key: "112",
    name: "Viktor",
    title: "the Machine Herald",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Viktor.png",
      sprite: "champion4.png",
      group: "champion",
      x: 336,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Vladimir",
    key: "8",
    name: "Vladimir",
    title: "the Crimson Reaper",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Vladimir.png",
      sprite: "champion4.png",
      group: "champion",
      x: 384,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Volibear",
    key: "106",
    name: "Volibear",
    title: "the Relentless Storm",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion4.png",
    image: {
      full: "Volibear.png",
      sprite: "champion4.png",
      group: "champion",
      x: 432,
      y: 96,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Warwick",
    key: "19",
    name: "Warwick",
    title: "the Uncaged Wrath of Zaun",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Warwick.png",
      sprite: "champion5.png",
      group: "champion",
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Xayah",
    key: "498",
    name: "Xayah",
    title: "the Rebel",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Xayah.png",
      sprite: "champion5.png",
      group: "champion",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Xerath",
    key: "101",
    name: "Xerath",
    title: "the Magus Ascendant",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Xerath.png",
      sprite: "champion5.png",
      group: "champion",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "XinZhao",
    key: "5",
    name: "Xin Zhao",
    title: "the Seneschal of Demacia",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "XinZhao.png",
      sprite: "champion5.png",
      group: "champion",
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Yasuo",
    key: "157",
    name: "Yasuo",
    title: "the Unforgiven",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Yasuo.png",
      sprite: "champion5.png",
      group: "champion",
      x: 192,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Yone",
    key: "777",
    name: "Yone",
    title: "the Unforgotten",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Yone.png",
      sprite: "champion5.png",
      group: "champion",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Yorick",
    key: "83",
    name: "Yorick",
    title: "Shepherd of Souls",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Yorick.png",
      sprite: "champion5.png",
      group: "champion",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Yuumi",
    key: "350",
    name: "Yuumi",
    title: "the Magical Cat",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Yuumi.png",
      sprite: "champion5.png",
      group: "champion",
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Zac",
    key: "154",
    name: "Zac",
    title: "the Secret Weapon",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Zac.png",
      sprite: "champion5.png",
      group: "champion",
      x: 384,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Zed",
    key: "238",
    name: "Zed",
    title: "the Master of Shadows",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Zed.png",
      sprite: "champion5.png",
      group: "champion",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Zeri",
    key: "221",
    name: "Zeri",
    title: "The Spark of Zaun",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Zeri.png",
      sprite: "champion5.png",
      group: "champion",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Ziggs",
    key: "115",
    name: "Ziggs",
    title: "the Hexplosives Expert",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Ziggs.png",
      sprite: "champion5.png",
      group: "champion",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Zilean",
    key: "26",
    name: "Zilean",
    title: "the Chronokeeper",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Zilean.png",
      sprite: "champion5.png",
      group: "champion",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Zoe",
    key: "142",
    name: "Zoe",
    title: "the Aspect of Twilight",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Zoe.png",
      sprite: "champion5.png",
      group: "champion",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Zyra",
    key: "143",
    name: "Zyra",
    title: "Rise of the Thorns",
    url: "https://dtneqrqtsogjewiotxnf.supabase.co/storage/v1/object/public/lolassets/sprite/champion5.png",
    image: {
      full: "Zyra.png",
      sprite: "champion5.png",
      group: "champion",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
  },
];
