export const SUMMONERS = [
  {
    id: "SummonerBarrier",
    key: "21",
    name: "Barrier",
    description:
      "Shields your champion from 105-411 damage (depending on champion level) for 2 seconds.",
    image: {
      full: "SummonerBarrier.png",
      sprite: "spell0.png",
      group: "spell",
      x: 0,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerBoost",
    key: "1",
    name: "Cleanse",
    description:
      "Removes all disables (excluding suppression and airborne) and summoner spell debuffs affecting your champion and lowers the duration of incoming disables by 65% for 3 seconds.",
    image: {
      full: "SummonerBoost.png",
      sprite: "spell0.png",
      group: "spell",
      x: 48,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerCherryFlash",
    key: "2202",
    name: "Flash",
    description:
      "Teleports your champion a short distance toward your cursor's location.",
    image: {
      full: "SummonerCherryFlash.png",
      sprite: "spell0.png",
      group: "spell",
      x: 96,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerCherryHold",
    key: "2201",
    name: "Flee",
    description:
      "Gain a short burst of Move Speed, increased while running away from enemy champions.",
    image: {
      full: "SummonerCherryHold.png",
      sprite: "spell0.png",
      group: "spell",
      x: 144,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerDot",
    key: "14",
    name: "Ignite",
    description:
      "Ignites target enemy champion, dealing 70-410 true damage (depending on champion level) over 5 seconds, grants you vision of the target, and reduces healing effects on them for the duration.",
    image: {
      full: "SummonerDot.png",
      sprite: "spell0.png",
      group: "spell",
      x: 192,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerExhaust",
    key: "3",
    name: "Exhaust",
    description:
      "Exhausts target enemy champion, reducing their Move Speed by 30%, and their damage dealt by 35% for 3 seconds.",
    image: {
      full: "SummonerExhaust.png",
      sprite: "spell0.png",
      group: "spell",
      x: 240,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerFlash",
    key: "4",
    name: "Flash",
    description:
      "Teleports your champion a short distance toward your cursor's location.",
    image: {
      full: "SummonerFlash.png",
      sprite: "spell0.png",
      group: "spell",
      x: 288,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerHaste",
    key: "6",
    name: "Ghost",
    description:
      "Your champion can move through units and gains 24 - 48% Move Speed (depending on champion level) for 15 seconds.",
    image: {
      full: "SummonerHaste.png",
      sprite: "spell0.png",
      group: "spell",
      x: 336,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerHeal",
    key: "7",
    name: "Heal",
    description:
      "Restores 80-318 Health and grants 30% Move Speed for 1 second to you and target allied champion. This healing is halved for units recently affected by Summoner Heal.",
    image: {
      full: "SummonerHeal.png",
      sprite: "spell0.png",
      group: "spell",
      x: 384,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerMana",
    key: "13",
    name: "Clarity",
    description:
      "Restores 50% of your champion's maximum Mana. Also restores allies for 25% of their maximum Mana.",
    image: {
      full: "SummonerMana.png",
      sprite: "spell0.png",
      group: "spell",
      x: 432,
      y: 0,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerPoroRecall",
    key: "30",
    name: "To the King!",
    description: "Quickly travel to the Poro King's side.",
    image: {
      full: "SummonerPoroRecall.png",
      sprite: "spell0.png",
      group: "spell",
      x: 0,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerPoroThrow",
    key: "31",
    name: "Poro Toss",
    description:
      "Toss a Poro at your enemies. If it hits, you can quickly travel to your target as a follow up.",
    image: {
      full: "SummonerPoroThrow.png",
      sprite: "spell0.png",
      group: "spell",
      x: 48,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerSmite",
    key: "11",
    name: "Smite",
    description: "Deals 600-1200 true damage to target monster or minion.",
    image: {
      full: "SummonerSmite.png",
      sprite: "spell0.png",
      group: "spell",
      x: 96,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerSnowURFSnowball_Mark",
    key: "39",
    name: "Mark",
    description:
      "Throw a snowball in a straight line at your enemies. If it hits an enemy, they become marked, granting True Sight, and your champion can quickly travel to the marked target as a follow up.",
    image: {
      full: "SummonerSnowURFSnowball_Mark.png",
      sprite: "spell0.png",
      group: "spell",
      x: 144,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerSnowball",
    key: "32",
    name: "Mark",
    description:
      "Throw a snowball in a straight line at your enemies. If it hits an enemy, they become marked, granting True Sight, and your champion can quickly travel to the marked target as a follow up.",
    image: {
      full: "SummonerSnowball.png",
      sprite: "spell0.png",
      group: "spell",
      x: 192,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "SummonerTeleport",
    key: "12",
    name: "Teleport",
    description:
      "After channeling for 4 seconds, teleports your champion to target allied structure. Upgrades to Unleashed Teleport at 14 minutes, which teleports your champion to target allied structure, minion, or ward.",
    image: {
      full: "SummonerTeleport.png",
      sprite: "spell0.png",
      group: "spell",
      x: 240,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Summoner_UltBookPlaceholder",
    key: "54",
    name: "Placeholder",
    description:
      "This slot will be replaced by another champion's ultimate selected at the start of the game. There will be 30 seconds to select an ultimate. Be prepared!",
    image: {
      full: "Summoner_UltBookPlaceholder.png",
      sprite: "spell0.png",
      group: "spell",
      x: 288,
      y: 48,
      w: 48,
      h: 48,
    },
  },
  {
    id: "Summoner_UltBookSmitePlaceholder",
    key: "55",
    name: "Placeholder and Attack-Smite",
    description:
      "This slot will be replaced by another champion's ultimate and you will gain Attack-Smite. There will be 30 seconds to select an ultimate. Be prepared!",
    image: {
      full: "Summoner_UltBookSmitePlaceholder.png",
      sprite: "spell0.png",
      group: "spell",
      x: 336,
      y: 48,
      w: 48,
      h: 48,
    },
  },
];
