import "./globals.css";
import "./css/champion-id-48.css";
import "./css/champion-id-24.css";
import "./css/champion-id-16.css";
import "./css/item-id-24.css";
import "./css/summoner-id-24.css";
import "tippy.js/dist/tippy.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./auth/Auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LoLStats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <div className="flex flex-col md:flex-row pt-[52px] min-h-screen">
            <div className="mx-auto xl:basis-[1024px] w-full bg-slate-700">
              {children}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
