import "./globals.css";
import "./css/champion-id-48.css";
import "./css/champion-id-24.css";
import "./css/champion-id-16.css";
import "./css/item-id-24.css";
import "./css/summoner-id-24.css";
import "tippy.js/dist/tippy.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import FriendList from "./components/FriendList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LoLStats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex flex-col md:flex-row pt-[68px] min-h-screen">
          <div className="mx-auto xl:basis-[1024px] w-full bg-slate-700">
            {children}
          </div>
          <FriendList className="relative right-0 basis-[200px] h-auto bg-slate-750 shrink-0" />
        </div>
      </body>
    </html>
  );
}
