export const regions: { [key: string]: string } = {
  eune: "eun1",
  euw: "euw1",
  br: "br1",
  lan: "la1",
  las: "la2",
  na: "na1",
  oce: "oc1",
  ru: "ru1",
  tr: "tr1",
  jp: "jp1",
  kr: "kr",
  ph: "ph2",
  sg: "sg2",
  tw: "tw2",
  th: "th2",
  vn: "vn2",
  pbe: "pbe",
};

export const servers: { [key: string]: string } = {
  eune: "europe",
  euw: "europe",
  br: "americas",
  lan: "americas",
  las: "americas",
  na: "americas",
  oce: "sea",
  ru: "asia",
  tr: "europe",
  jp: "asia",
  kr: "asia",
  ph: "asia",
  sg: "asia",
  tw: "asia",
  th: "asia",
  vn: "asia",
  pbe: "pbe",
};

export const queues: { [key: number]: string } = {
  0: "Custom",
  72: "1v1 Snowdown",
  73: "2v2 Snowdown",
  75: "6v6 Hexakill",
  76: "Ultra Rapid Fire",
  78: "One For All: Aram",
  98: "6v6 Hexakill",
  100: "Butcher's Bridge",
  310: "Nemesis",
  313: "Black Market Brawlers",
  317: "Definitely Not Dominion",
  325: "All Random",
  400: "5v5 Draft Pick",
  420: "5v5 Ranked Solo",
  430: "5v5 Blind Pick",
  440: "5v5 Ranked Flex",
  450: "5v5 ARAM",
  600: "Blood Hunt Assassin",
  610: "Dark Star",
  700: "Clash",
  720: "ARAM Clash",
  830: "Co-op vs. AI",
  840: "Co-op vs. AI",
  850: "Co-op vs. AI",
  900: "ARURF",
  910: "Ascension",
  920: "Poro King",
  940: "Nexus Siege",
  950: "Doom Bots Voting",
  960: "Doom Bots Standard",
  980: "Star Guardian Invasion: Normal",
  990: "Star Guardian Invasion: Onslaught",
  1000: "PROJECT: Hunters",
  1010: "Snow ARURF",
  1020: "One for All",
  1030: "Odyssey Extraction: Intro",
  1040: "Odyssey Extraction: Cadet",
  1050: "Odyssey Extraction: Crewmember",
  1060: "Odyssey Extraction: Captain",
  1070: "Odyssey Extraction: Onslaught",
  1090: "Teamfight Tactics",
  1100: "Ranked Teamfight Tactics",
  1110: "Teamfight Tactics Tutorial",
  1111: "Teamfight Tactics test",
  1300: "Nexus Blitz",
  1400: "Ultimate Spellbook",
  1700: "Arena",
  1900: "Pick URF",
  2000: "Tutorial 1",
  2010: "Tutorial 2",
  2020: "Tutorial 3",
};

export const spells: { [key: number]: string } = {
  1: "SummonerBoost",
  3: "SummonerExhaust",
  4: "SummonerFlash",
  6: "SummonerHaste",
  7: "SummonerHeal",
  11: "SummonerSmite",
  12: "SummonerTeleport",
  13: "SummonerMana",
  14: "SummonerDot",
  21: "SummonerBarrier",
  30: "SummonerPoroRecall",
  31: "SummonerPoroThrow",
  32: "SummonerSnowball",
  39: "SummonerSnowURFSnowball_Mark",
  54: "Summoner_UltBookPlaceholder",
  55: "Summoner_UltBookSmitePlaceholder",
  2202: "SummonerCherryFlash",
  2201: "SummonerCherryHold",
};

export const runes: { [key: number]: string } = {
  8100: "7200_Domination.png",
  8300: "7203_Whimsy.png",
  8000: "7201_Precision.png",
  8400: "7204_Resolve.png",
  8200: "7202_Sorcery.png",
  8112: "Domination/Electrocute/Electrocute.png",
  8124: "Domination/Predator/Predator.png",
  8128: "Domination/DarkHarvest/DarkHarvest.png",
  9923: "Domination/HailOfBlades/HailOfBlades.png",
  8351: "Inspiration/GlacialAugment/GlacialAugment.png",
  8360: "Inspiration/UnsealedSpellbook/UnsealedSpellbook.png",
  8369: "Inspiration/FirstStrike/FirstStrike.png",
  8005: "Precision/PressTheAttack/PressTheAttack.png",
  8008: "Precision/LethalTempo/LethalTempoTemp.png",
  8021: "Precision/FleetFootwork/FleetFootwork.png",
  8010: "Precision/Conqueror/Conqueror.png",
  8437: "Resolve/GraspOfTheUndying/GraspOfTheUndying.png",
  8439: "Resolve/VeteranAftershock/VeteranAftershock.png",
  8465: "Resolve/Guardian/Guardian.png",
  8214: "Sorcery/SummonAery/SummonAery.png",
  8229: "Sorcery/ArcaneComet/ArcaneComet.png",
  8230: "Sorcery/PhaseRush/PhaseRush.png",
};
